<a href="https://colab.research.google.com/github/feandresilva/exercicios_Pandas/blob/main/dataframe_matriculas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import plotly.express as px
from scipy import stats
from scipy.stats import skew
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency
from scipy.stats.contingency import association
df_matriculas = pd.read_csv("https://cognitrilha.com.br/datasets/matriculas_inep2019a2023.csv.gz", encoding= "iso-8859-1", sep=";")
df_matriculas.head(5)

,nu_ano_censo,cod_ibge,tp_modalidade_ensino,co_ies,tp_rede,co_cine_rotulo,grau_academico,sexo,n_matricula
0,2020,3500105,Presencial,1292,Pública,0113P01,Licenciatura,Masculino,5
1,2020,3500105,Presencial,1292,Pública,0114B01,Licenciatura,Masculino,15
2,2020,3500105,Presencial,1292,Pública,0114E03,Licenciatura,Masculino,77
3,2020,3500105,Presencial,1292,Pública,0114H01,Licenciatura,Masculino,13
4,2020,3500105,Presencial,1292,Pública,0114M01,Licenciatura,Masculino,18

Exiba as 10 primeiras linhas da tabela

Exiba os dados usando .info() e .describe()

Faça gráficos de pizza para as seguintes variáveis qualitativas nominais: tp_modalidade_ensino		tp_rede		grau_academico	sexo


Faça um gráfico de barras empilhado (bar stacked) que mostre a evolução das inscrições por grau_academico

Exiba a correlação entre as colunas grau_academico e sexo (utilize pd.crosstab)

Exiba a correlação entre as colunas grau_academico e sexo.
Em seguida, utilize o scipy.stats.chi2_contingency para validar a correlação entre essas variáveis.
Considere p < 0.05 → existe evidência de associação.
p >= 0.05 → não há evidência de associação.

Obtenha o valor v de Cramér para medir a correlação entre as variáveis grau_academico e sexo.

Considere 0 <= V <= 1;
0 = independência perfeita;
1 = associação perfeita;

Utilize scipy.stats.contingency.association com method="cramer".

Exiba a tabela unificada que mostre os nomes dos cursos

Exiba o top 5 cursos por quantidade de novas matrículas.

Exiba o maior curso por quantidade de matrículas para cada grau academico.

Crie um dataframe a partir do dataset abaixo:
https://cognitrilha.com.br/datasets/DTB_2024/RELATORIO_DTB_BRASIL_2024_MUNICIPIOS.xls

Exiba as primeiras 5 linhas do dataset.

Unifique o dataframe de matrículas com o dataframe de municípios, com base na coluna cod_ibge.

Exiba o top 5 cursos por número de matrículas do estado SP.

Exiba o top 5 cursos por número de matrículas da região Sudeste.

Crie um DataFrame a partir dos dados  no arquivo abaixo:
https://cognitrilha.com.br/datasets/ies_2026.xls

Exiba as 5 primeiras linhas do dataframe

Faça um dataframe unificado (merge) através da coluna "cod_ies" = "Código Mantenedora"

In [ ]:
#Exiba as 10 primeiras linhas da tabela
df_matriculas.head(10)

,nu_ano_censo,cod_ibge,tp_modalidade_ensino,co_ies,tp_rede,co_cine_rotulo,grau_academico,sexo,n_matricula
0,2020,3500105,Presencial,1292,Pública,0113P01,Licenciatura,Masculino,5
1,2020,3500105,Presencial,1292,Pública,0114B01,Licenciatura,Masculino,15
2,2020,3500105,Presencial,1292,Pública,0114E03,Licenciatura,Masculino,77
3,2020,3500105,Presencial,1292,Pública,0114H01,Licenciatura,Masculino,13
4,2020,3500105,Presencial,1292,Pública,0114M01,Licenciatura,Masculino,18
5,2020,3500105,Presencial,1292,Pública,0212D02,Bacharelado,Masculino,5
6,2020,3500105,Presencial,1292,Pública,0311E01,Bacharelado,Masculino,6
7,2020,3500105,Presencial,1292,Pública,0313P01,Bacharelado,Masculino,36
8,2020,3500105,Presencial,1292,Pública,0411C01,Bacharelado,Masculino,24
9,2020,3500105,Presencial,1292,Pública,0413A01,Bacharelado,Masculino,50

In [ ]:
#Exiba os dados usando .info() e .describe()
display(df_matriculas.info())
display(df_matriculas.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 856657 entries, 0 to 856656
Data columns (total 9 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   nu_ano_censo          856657 non-null  int64
 1   cod_ibge              856657 non-null  int64
 2   tp_modalidade_ensino  856657 non-null  object
 3   co_ies                856657 non-null  int64
 4   tp_rede               856657 non-null  object
 5   co_cine_rotulo        856657 non-null  object
 6   grau_academico        856657 non-null  object
 7   sexo                  856657 non-null  object
 8   n_matricula           856657 non-null  int64
dtypes: int64(4), object(5)
memory usage: 58.8+ MB

None

        nu_ano_censo      cod_ibge         co_ies    n_matricula
count  856657.000000  8.566570e+05  856657.000000  856657.000000
mean     2021.677340  3.530640e+06    1690.024313      12.444151
std         1.251969  1.723085e+04    3497.539289      75.978310
min      2019.000000  3.500105e+06       2.000000       0.000000
25%      2021.000000  3.515509e+06     322.000000       0.000000
50%      2022.000000  3.530300e+06     671.000000       1.000000
75%      2023.000000  3.548708e+06    1472.000000       4.000000
max      2023.000000  3.557303e+06   28988.000000   11172.000000

In [ ]:
#Faça gráficos de pizza para as seguintes variáveis qualitativas nominais: tp_modalidade_ensino
df_modalidades = df_matriculas["tp_modalidade_ensino"].value_counts()
df_modalidades = df_modalidades.reset_index()
df_modalidades = df_modalidades.rename(columns={"count": "valores"})
fig = px.pie(df_modalidades, values="valores", names="tp_modalidade_ensino")
fig.show()

In [ ]:
#Faça gráficos de pizza para as seguintes variáveis qualitativas nominais: tp_rede
df_tipo_rede = df_matriculas["tp_rede"].value_counts()
df_tipo_rede = df_tipo_rede.reset_index()
df_tipo_rede = df_tipo_rede.rename(columns={"count": "valores", "tp_rede": "tipo_rede"})
fig = px.pie(df_tipo_rede, values="valores", names="tipo_rede")
fig.show()

In [ ]:
#Faça gráficos de pizza para as seguintes variáveis qualitativas nominais: grau_academico
df_grau_academico = df_matriculas["grau_academico"].value_counts()
df_grau_academico = df_grau_academico.reset_index()
df_grau_academico = df_grau_academico.rename(columns={"count": "valores"})
fig = px.pie(df_grau_academico, values="valores", names="grau_academico")
fig.show()

In [ ]:
#Faça gráficos de pizza para as seguintes variáveis qualitativas nominais: sexo
df_sexo = df_matriculas["sexo"].value_counts()
df_sexo = df_sexo.reset_index()
df_sexo = df_sexo.rename(columns={"count": "valores"})
fig = px.pie(df_sexo, values="valores", names="sexo")
fig.show()

In [ ]:
#Faça um gráfico de barras empilhado (bar stacked) que mostre a evolução das inscrições por grau_academico
df_evolucao_academica = df_matriculas.groupby("nu_ano_censo")["grau_academico"].value_counts()
df_evolucao_academica = df_evolucao_academica.reset_index()
df_evolucao_academica = df_evolucao_academica.rename(columns={"count": "Valores", "nu_ano_censo": "Ano"})
fig = px.bar(df_evolucao_academica, x="Ano", y="Valores", color= "grau_academico")
fig.show()

In [ ]:
#Exiba a correlação entre as colunas grau_academico e sexo (utilize pd.crosstab)
df_correlacao = pd.crosstab(df_matriculas["grau_academico"], df_matriculas["sexo"])
df_correlacao

sexo            Feminino  Masculino
grau_academico
Bacharelado       138505     140217
Licenciatura       87645      85110
Não aplica           901        905
Tecnológico       200098     203276

In [ ]:
#Exiba a correlação entre as colunas grau_academico e sexo.
#Em seguida, utilize o scipy.stats.chi2_contingency para validar a correlação entre essas variáveis.
#Considere p < 0.05 → existe evidência de associação.
#p >= 0.05 → não há evidência de associação.

df_academico_modalidade_correlacao = pd.crosstab(df_matriculas["grau_academico"], df_matriculas["sexo"])
res = chi2_contingency(df_academico_modalidade_correlacao)
res.pvalue

np.float64(2.6892432079268502e-14)

In [ ]:
#Obtenha o valor v de Cramér para medir a correlação entre as variáveis grau_academico e sexo.

#Considere 0 <= V <= 1;
#0 = independência perfeita;
#1 = associação perfeita;

#Utilize scipy.stats.contingency.association com method="cramer".

association(df_academico_modalidade_correlacao, method="cramer")

0.008795087728900766

In [ ]:
#Exiba a tabela unificada que mostre os nomes dos cursos (utilize a lista de codigos do inep: https://repositorio.seade.gov.br/dataset/cb99a06d-7b66-4e58-bd3f-2a7e52fa8607/resource/b6abe70a-3cff-41a7-935f-23892d1c02b8/download/cine_inep.csv)

df_matriculas2 = pd.read_csv("https://cognitrilha.com.br/datasets/cine_inep.csv", encoding= "iso-8859-1", sep=";")
df_matriculas_unificado = df_matriculas.merge(df_matriculas2, on="co_cine_rotulo", how="left")
df_matriculas_unificado

,nu_ano_censo,cod_ibge,tp_modalidade_ensino,co_ies,tp_rede,co_cine_rotulo,grau_academico,sexo,n_matricula,no_cine_rotulo
0,2020,3500105,Presencial,1292,Pública,0113P01,Licenciatura,Masculino,5,Pedagogia
1,2020,3500105,Presencial,1292,Pública,0114B01,Licenciatura,Masculino,15,Biologia formação de professor
2,2020,3500105,Presencial,1292,Pública,0114E03,Licenciatura,Masculino,77,Educação física formação de professor
3,2020,3500105,Presencial,1292,Pública,0114H01,Licenciatura,Masculino,13,História formação de professor
4,2020,3500105,Presencial,1292,Pública,0114M01,Licenciatura,Masculino,18,Matemática formação de professor
...,...,...,...,...,...,...,...,...,...,...
856652,2023,3526902,Presencial,27029,Privada,0912M01,Bacharelado,Masculino,17,Medicina
856653,2023,3542602,Presencial,28985,Pública,0688P01,Tecnológico,Masculino,55,Programas interdisciplinares abrangendo comput...
856654,2023,3505500,Presencial,28986,Pública,0413G11,Tecnológico,Masculino,41,Gestão hospitalar
856655,2023,3557006,Presencial,28988,Pública,0732C02,Tecnológico,Masculino,43,Controle de obras
856656,2023,3557006,Presencial,28988,Pública,0688P01,Tecnológico,Masculino,61,Programas interdisciplinares abrangendo comput...

In [ ]:
#Exiba o top 5 cursos por quantidade de novas matrículas.
df_matriculas_unificado
df_top_cursos = df_matriculas_unificado.groupby("no_cine_rotulo")["n_matricula"].sum().sort_values(ascending=False)
df_top_cursos.head(5)

no_cine_rotulo
Pedagogia                 946115
Direito                   775581
Administração             755556
Sistemas de informação    424739
Psicologia                402332
Name: n_matricula, dtype: int64

In [ ]:
#Exiba o maior curso por quantidade de matrículas para cada grau academico
df_por_grau = df_matriculas_unificado.groupby(["grau_academico", "no_cine_rotulo"])["n_matricula"].sum().sort_values(ascending=False)
df_por_grau

grau_academico  no_cine_rotulo
Licenciatura    Pedagogia                   946115
Bacharelado     Direito                     775581
                Administração               755498
                Psicologia                  402323
                Enfermagem                  373607
                                             ...
                Desenho industrial               5
                Saúde coletiva                   3
Tecnológico     Ciência política                 3
                Produção sucroalcooleira         1
                Letras escrita criativa          0
Name: n_matricula, Length: 374, dtype: int64

In [ ]:
#Crie um dataframe a partir do dataset abaixo e exiba as 5 primeiras linhas
#https://cognitrilha.com.br/datasets/DTB_2024/RELATORIO_DTB_BRASIL_2024_MUNICIPIOS.xls

df_municipios = pd.read_excel("https://cognitrilha.com.br/datasets/DTB_2024/RELATORIO_DTB_BRASIL_2024_MUNICIPIOS.xls", skiprows=6)
df_municipios.head(5)

,UF,Nome_UF,Região Geográfica Intermediária,Nome Região Geográfica Intermediária,Região Geográfica Imediata,Nome Região Geográfica Imediata,Município,Código Município Completo,Nome_Município,Unnamed: 9
0,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,NaN
1,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,379,1100379,Alto Alegre dos Parecis,NaN
2,11,Rondônia,1101,Porto Velho,110002,Ariquemes,403,1100403,Alto Paraíso,NaN
3,11,Rondônia,1102,Ji-Paraná,110004,Ji-Paraná,346,1100346,Alvorada D'Oeste,NaN
4,11,Rondônia,1101,Porto Velho,110002,Ariquemes,23,1100023,Ariquemes,NaN

In [ ]:
#Unifique o dataframe de matrículas com o dataframe de municípios, com base na coluna cod_ibge.
df_municipios = df_municipios.rename(columns={"Código Município Completo": "cod_ibge"})
df_matriculas_localidade = df_matriculas_unificado.merge(df_municipios, on="cod_ibge", how="left")
df_matriculas_localidade["Nome_UF"].unique()

array(['São Paulo'], dtype=object)

In [ ]:
#Exiba o top 5 cursos por número de matrículas do estado SP.
df_matriculas_SP = df_matriculas_localidade[df_matriculas_localidade["Nome_UF"]== "São Paulo"]
df_matriculas_SP = df_matriculas_SP.groupby("no_cine_rotulo")["n_matricula"].sum().sort_values(ascending=False)
df_matriculas_SP.head(5)

no_cine_rotulo
Pedagogia                 946115
Direito                   775581
Administração             755556
Sistemas de informação    424739
Psicologia                402332
Name: n_matricula, dtype: int64

In [ ]:
#Exiba o top 5 cursos por número de matrículas da região Sudeste.
df_sudeste = df_matriculas_localidade[(df_matriculas_localidade["Nome_UF"] == "São Paulo") | (df_matriculas_localidade["Nome_UF"] == "Rio de Janeiro") | (df_matriculas_localidade["Nome_UF"]== "Minas Gerais") | (df_matriculas_localidade["Nome_UF"] == "Espírito Santo")]
df_sudeste["Nome_UF"].unique()

array(['São Paulo'], dtype=object)

In [ ]:
#Crie um DataFrame a partir dos dados  no arquivo abaixo:
#https://cognitrilha.com.br/datasets/ies_2026.xls

#Exiba as 5 primeiras linhas do dataframe

df = pd.read_excel("https://cognitrilha.com.br/datasets/ies_2026.xls", skiprows=4)
df.head(5)

,Código Mantenedora,Razão Social,CNPJ,Natureza Jurídica,Código IES,Instituição(IES),Sigla,Telefone,Sitio,e-Mail,...,CI,Ano CI,CI-EaD,Ano CI-EaD,IGC,Ano IGC,Reitor/Dirigente Principal,Representante Legal,Sinalizações Vigentes,Situação da IES
0,230,ASSOCIACAO DE ENSINO SUPERIOR DE NOVA IGUACU,30.834.196/0001-80,Privada sem fins lucrativos,2565,ABEU - CENTRO UNIVERSITÁRIO (UNIABEU),UNIABEU,(21) 2104-0460,www.uniabeu.edu.br,marcelo.rosa@abeugraduacao.com.br,...,5,2023.0,4,2018.0,3,2023.0,NaN,NaN,NaN,Ativa
1,18344,COMANDO DA AERONAUTICA,00.394.429/0111-45,Pessoa Jurídica de Direito Público - Federal,26777,ACADEMIA DA FORÇA AÉREA (AFA),AFA,(19)3565 7000,https://www2.fab.mil.br/afa/,dpl.direns@gmail.com,...,-,NaN,-,NaN,-,NaN,NaN,NaN,NaN,Ativa
2,18177,CORPO DE BOMBEIROS MILITAR DE MINAS GERAIS,03.389.126/0001-98,Pessoa Jurídica de Direito Público - Estadual,26238,ACADEMIA DE BOMBEIROS MILITAR (ABM),ABM,3133119179,NaN,abm.ste@bombeiros.mg.gov.br,...,-,NaN,-,NaN,-,NaN,NaN,NaN,NaN,Ativa
3,19728,FUNDO DE MELHORIA DA POLICIA CIVIL - FUMPC,07.188.579/0001-07,Fundo Público da Administração Direta Estadual...,30426,Academia de Polícia Civil de Santa Catarina (A...,ACADEPOL/SC,NaN,https://acadepol.sc.gov.br/,acadepol@pc.sc.gov.br,...,-,NaN,-,NaN,-,NaN,NaN,NaN,NaN,Ativa
4,17963,POLICIA MILITAR DO ESTADO DE MINAS GERAIS,16.695.025/0001-97,Pessoa Jurídica de Direito Público - Estadual,25613,ACADEMIA DE POLÍCIA MILITAR DE MINAS GERAIS (APM),APM,(31) 2123-9484,https://www.policiamilitar.mg.gov.br/portal-pm...,divisaodeensino.apm@pmmg.mg.gov.br,...,-,NaN,-,NaN,-,NaN,NaN,NaN,NaN,Ativa

In [ ]:
#Faça um dataframe unificado (merge) através da coluna "co_ies" = "Código Mantenedora"
df = df.rename(columns={"Código IES": "co_ies"})
df_unificado2 = df.merge(df_matriculas_localidade, on="co_ies", how="inner")
df_unificado2

,Código Mantenedora,Razão Social,CNPJ,Natureza Jurídica,co_ies,Instituição(IES),Sigla,Telefone,Sitio,e-Mail,...,no_cine_rotulo,UF_y,Nome_UF,Região Geográfica Intermediária,Nome Região Geográfica Intermediária,Região Geográfica Imediata,Nome Região Geográfica Imediata,Município_y,Nome_Município,Unnamed: 9
0,2274,INSTITUICAO BAIANA DE ENSINO SUPERIOR LTDA,05.817.107/0001-40,Privada com fins lucrativos,3588,Afya Centro Universitário da Bahia (-),-,(79) 981146586,www.unidompedro.edu.br,adriano.douglas@afya.com.br,...,Pedagogia,35,São Paulo,3501,São Paulo,350001,São Paulo,18800,Guarulhos,NaN
1,2274,INSTITUICAO BAIANA DE ENSINO SUPERIOR LTDA,05.817.107/0001-40,Privada com fins lucrativos,3588,Afya Centro Universitário da Bahia (-),-,(79) 981146586,www.unidompedro.edu.br,adriano.douglas@afya.com.br,...,Segurança privada,35,São Paulo,3501,São Paulo,350001,São Paulo,18800,Guarulhos,NaN
2,938,CENTRO DE ENSINO SAO LUCAS LTDA,84.596.170/0001-70,Privada com fins lucrativos,1414,Afya Centro Universitário São Lucas (Afya São ...,Afya São Lucas,(69) 3211-8000,https://portovelho.afya.com.br/,reitoria.saolucas@afya.com.br,...,Educação física,35,São Paulo,3503,Bauru,350011,Botucatu,7506,Botucatu,NaN
3,938,CENTRO DE ENSINO SAO LUCAS LTDA,84.596.170/0001-70,Privada com fins lucrativos,1414,Afya Centro Universitário São Lucas (Afya São ...,Afya São Lucas,(69) 3211-8000,https://portovelho.afya.com.br/,reitoria.saolucas@afya.com.br,...,Pedagogia,35,São Paulo,3511,São José dos Campos,350049,São José dos Campos,8504,Caçapava,NaN
4,938,CENTRO DE ENSINO SAO LUCAS LTDA,84.596.170/0001-70,Privada com fins lucrativos,1414,Afya Centro Universitário São Lucas (Afya São ...,Afya São Lucas,(69) 3211-8000,https://portovelho.afya.com.br/,reitoria.saolucas@afya.com.br,...,Contabilidade,35,São Paulo,3511,São José dos Campos,350049,São José dos Campos,8504,Caçapava,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853280,17982,SOCIEDADE EDUCACAO E GESTAO DE EXCELENCIA I VI...,37.745.762/0001-27,Privada com fins lucrativos,664,UNIVERSIDADE VILA VELHA (UVV),UVV,(27) 3421-2000,www.uvv.br,uvv@uvv.br;elaine@uvv.br,...,Publicidade e propaganda,35,São Paulo,3501,São Paulo,350001,São Paulo,50308,São Paulo,NaN
853281,17982,SOCIEDADE EDUCACAO E GESTAO DE EXCELENCIA I VI...,37.745.762/0001-27,Privada com fins lucrativos,664,UNIVERSIDADE VILA VELHA (UVV),UVV,(27) 3421-2000,www.uvv.br,uvv@uvv.br;elaine@uvv.br,...,Comércio exterior,35,São Paulo,3501,São Paulo,350001,São Paulo,50308,São Paulo,NaN
853282,17982,SOCIEDADE EDUCACAO E GESTAO DE EXCELENCIA I VI...,37.745.762/0001-27,Privada com fins lucrativos,664,UNIVERSIDADE VILA VELHA (UVV),UVV,(27) 3421-2000,www.uvv.br,uvv@uvv.br;elaine@uvv.br,...,Gestão de pessoas,35,São Paulo,3501,São Paulo,350001,São Paulo,50308,São Paulo,NaN
853283,17982,SOCIEDADE EDUCACAO E GESTAO DE EXCELENCIA I VI...,37.745.762/0001-27,Privada com fins lucrativos,664,UNIVERSIDADE VILA VELHA (UVV),UVV,(27) 3421-2000,www.uvv.br,uvv@uvv.br;elaine@uvv.br,...,Marketing,35,São Paulo,3501,São Paulo,350001,São Paulo,50308,São Paulo,NaN
853284,17982,SOCIEDADE EDUCACAO E GESTAO DE EXCELENCIA I VI...,37.745.762/0001-27,Privada com fins lucrativos,664,UNIVERSIDADE VILA VELHA (UVV),UVV,(27) 3421-2000,www.uvv.br,uvv@uvv.br;elaine@uvv.br,...,Pedagogia,35,São Paulo,3501,São Paulo,350001,São Paulo,50308,São Paulo,NaN

In [ ]:
#Filtre apenas as colunas:

#nu_ano_censo, tp_modalidade_ensino, tp_rede, grau_academico, sexo, n_matricula, Nome_UF, Nome_Município, Instituição(IES), Categoria, Data do Ato de Criação da IES e Situação da IES

df_unificado2_filtrado = df_unificado2[["co_ies", "nu_ano_censo", "tp_modalidade_ensino", "tp_rede", "grau_academico", "sexo", "n_matricula", "Nome_UF", "Nome_Município", "Instituição(IES)", "Categoria", "Data do Ato de Criação da IES", "Situação da IES"]]
df_unificado2_filtrado

,co_ies,nu_ano_censo,tp_modalidade_ensino,tp_rede,grau_academico,sexo,n_matricula,Nome_UF,Nome_Município,Instituição(IES),Categoria,Data do Ato de Criação da IES,Situação da IES
0,3588,2019,EAD,Privada,Licenciatura,Feminino,1,São Paulo,Guarulhos,Afya Centro Universitário da Bahia (-),Privada,2005-05-16,Ativa
1,3588,2019,EAD,Privada,Tecnológico,Feminino,1,São Paulo,Guarulhos,Afya Centro Universitário da Bahia (-),Privada,2005-05-16,Ativa
2,1414,2020,EAD,Privada,Bacharelado,Masculino,2,São Paulo,Botucatu,Afya Centro Universitário São Lucas (Afya São ...,Privada,1999-12-07,Ativa
3,1414,2020,EAD,Privada,Licenciatura,Masculino,6,São Paulo,Caçapava,Afya Centro Universitário São Lucas (Afya São ...,Privada,1999-12-07,Ativa
4,1414,2020,EAD,Privada,Bacharelado,Masculino,8,São Paulo,Caçapava,Afya Centro Universitário São Lucas (Afya São ...,Privada,1999-12-07,Ativa
...,...,...,...,...,...,...,...,...,...,...,...,...,...
853280,664,2023,EAD,Privada,Bacharelado,Masculino,0,São Paulo,São Paulo,UNIVERSIDADE VILA VELHA (UVV),Privada,1976-04-13,Ativa
853281,664,2023,EAD,Privada,Tecnológico,Masculino,1,São Paulo,São Paulo,UNIVERSIDADE VILA VELHA (UVV),Privada,1976-04-13,Ativa
853282,664,2023,EAD,Privada,Tecnológico,Masculino,0,São Paulo,São Paulo,UNIVERSIDADE VILA VELHA (UVV),Privada,1976-04-13,Ativa
853283,664,2023,EAD,Privada,Tecnológico,Masculino,0,São Paulo,São Paulo,UNIVERSIDADE VILA VELHA (UVV),Privada,1976-04-13,Ativa
853284,664,2023,EAD,Privada,Licenciatura,Masculino,0,São Paulo,São Paulo,UNIVERSIDADE VILA VELHA (UVV),Privada,1976-04-13,Ativa

In [ ]:
#Faça um df_final: Filtre apenas as linhas onde a coluna Situação da IES == "Ativa".
df_final = df_unificado2_filtrado[df_unificado2_filtrado["Situação da IES"] == "Ativa"]
df_final.head(5)

,co_ies,nu_ano_censo,tp_modalidade_ensino,tp_rede,grau_academico,sexo,n_matricula,Nome_UF,Nome_Município,Instituição(IES),Categoria,Data do Ato de Criação da IES,Situação da IES
0,3588,2019,EAD,Privada,Licenciatura,Feminino,1,São Paulo,Guarulhos,Afya Centro Universitário da Bahia (-),Privada,2005-05-16,Ativa
1,3588,2019,EAD,Privada,Tecnológico,Feminino,1,São Paulo,Guarulhos,Afya Centro Universitário da Bahia (-),Privada,2005-05-16,Ativa
2,1414,2020,EAD,Privada,Bacharelado,Masculino,2,São Paulo,Botucatu,Afya Centro Universitário São Lucas (Afya São ...,Privada,1999-12-07,Ativa
3,1414,2020,EAD,Privada,Licenciatura,Masculino,6,São Paulo,Caçapava,Afya Centro Universitário São Lucas (Afya São ...,Privada,1999-12-07,Ativa
4,1414,2020,EAD,Privada,Bacharelado,Masculino,8,São Paulo,Caçapava,Afya Centro Universitário São Lucas (Afya São ...,Privada,1999-12-07,Ativa

In [ ]:
#Agrupe por ano e IES e some o numero de matriculas, para exibir a IES que teve o maior número de matrículas de cada ano.
df_IES_mais_matriculas = df_final.groupby(["nu_ano_censo", "Instituição(IES)"])["n_matricula"].sum().sort_values(ascending=False)
df_IES_mais_matriculas = df_IES_mais_matriculas.reset_index()
df_IES_mais_matriculas

,nu_ano_censo,Instituição(IES),n_matricula
0,2020,UNIVERSIDADE PAULISTA (UNIP),246766
1,2019,UNIVERSIDADE PAULISTA (UNIP),239902
2,2021,UNIVERSIDADE PAULISTA (UNIP),223036
3,2022,UNIVERSIDADE PAULISTA (UNIP),193841
4,2020,UNIVERSIDADE NOVE DE JULHO (UNINOVE),188178
...,...,...,...
3119,2022,CENTRO UNIVERSITÁRIO RITTER DOS REIS (UNIRITTER),0
3120,2023,CENTRO UNIVERSITÁRIO IBMR,0
3121,2023,FACULDADE UNICPO (FACULDADE UNICPO),0
3122,2023,Faculdades Integradas União Bandeirante,0
3123,2021,Faculdade FIA de Gestão e Tecnologia (FFGT),0

In [ ]:
#Agora, exiba as IES publicas com o maior número de matrículas de cada ano.
df_IES_publicas = df_final[df_final["Categoria"] == "Publica"]
df_IES_publicas_mais_matriculas = df_IES_publicas.groupby(["nu_ano_censo", "Instituição(IES)"])["n_matricula"].sum().sort_values(ascending=False)
df_IES_publicas_mais_matriculas

nu_ano_censo  Instituição(IES)
2023          Fundação Universidade Virtual do Estado de São Paulo (UNIVESP)    67042
2019          UNIVERSIDADE DE SÃO PAULO (USP)                                   65156
2020          UNIVERSIDADE DE SÃO PAULO (USP)                                   64276
2022          UNIVERSIDADE DE SÃO PAULO (USP)                                   63977
2021          UNIVERSIDADE DE SÃO PAULO (USP)                                   63276
                                                                                ...
2020          UNIVERSIDADE FEDERAL DE JUIZ DE FORA (UFJF)                           3
2023          UNIVERSIDADE FEDERAL DE OURO PRETO (UFOP)                             3
2019          UNIVERSIDADE FEDERAL DE JUIZ DE FORA (UFJF)                           3
2022          UNIVERSIDADE FEDERAL DE JUIZ DE FORA (UFJF)                           1
              UNIVERSIDADE FEDERAL DE ALFENAS (UNIFAL-MG)                           0
Name: n_matricula, Length: 580, dtype: int64

In [ ]:
df_final.to_excel("/content/drive/MyDrive/Colab Notebooks/df_final_matriculas.xlsx". index=False)