<a href="https://colab.research.google.com/github/feandresilva/exercicios_Pandas/blob/main/ODS_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
df_ODS = pd.read_csv("https://github.com/marcelovc785/AP2_PML_8001/raw/main/IDSC_BR_AP2_E01d2G01.csv", encoding="iso-8859-1", sep= ";", decimal = ",")
df_ODS.head()

,id,Territorialidade,População_Ref,Pontuação Indice ODS 2022,Classificação 2022,2022 ODS 1,2022 ODS 3,2022 ODS 5,Pontuação Indice ODS 2019,Classificação 2019,2019 ODS 1,2019 ODS 3,2019 ODS 5
0,5200050.0,;Abadia de Goiás;GO;CO;,19128.0,48.06,2226.0,42.39,64.57,33.67,48.63,2109.0,44.36,39.52,33.67
1,3100104.0,;Abadia dos Dourados;MG;SE;,6272.0,45.65,3143.0,51.21,65.08,16.16,46.84,2688.0,53.63,69.53,16.16
2,5200100.0,;Abadiânia;GO;CO;,17228.0,49.36,1773.0,44.83,76.23,27.80,50.11,1648.0,43.71,60.24,27.80
3,3100203.0,;Abaeté;MG;SE;,22675.0,52.73,899.0,47.13,77.96,15.08,49.59,1801.0,47.60,57.21,15.08
4,1500107.0,;Abaetetuba;PA;N;,158188.0,37.92,5293.0,38.08,71.62,20.20,38.11,5215.0,37.64,56.52,20.20

Qual o estado da região Sudeste que teve o menor valor na média da “ODS 3 do
Ano 2022”, organizada por “UF”?


Qual a cidade do estado que reponde corretamente o item anterior, e que teve o valor da “ODS ano 2022” mais próximo da média do estado inteiro?


Qual foi a cidade do estado do Rio de Janeiro que teve o menor crescimento da “ODS 5” entre os anos 2019 e 2022


Aproximadamente, qual a média da "ODS 5" entre os anos 2019 e 2022 da região
Nordeste?


Qual foi o estado da região Nordeste que teve a maior média da coluna ODS 5 do ano 2022, organizada por “UF”?


Qual foi a cidade do estado que responde corretamente o item anterior que teve o
maior crescimento da Coluna ODS 5 entre os anos 2019 e 2022?

In [34]:
#Qual o estado da região Sudeste que teve o menor valor na média da “ODS 3 do Ano 2022”, organizada por “UF”?
df_ODS_sem_nulos = df_ODS.dropna(subset="Territorialidade")
df_ODS_UF = df_ODS_sem_nulos[(df_ODS_sem_nulos["Territorialidade"].str.split(";").str[3] == "SE")]
df_ODS_UF.groupby("Territorialidade")["2022 ODS 3"].mean().sort_values()

Territorialidade
;Estrela d'Oeste;SP;SE;    46.72
;Paranapuã;SP;SE;          48.58
;Linhares;ES;SE;           49.08
;Guapiara;SP;SE;           49.44
;Holambra;SP;SE;           49.59
                           ...
;Marapoama;SP;SE;          87.73
;União Paulista;SP;SE;     88.08
;Mariápolis;SP;SE;         88.21
;Dobrada;SP;SE;            88.23
;Nantes;SP;SE;             88.43
Name: 2022 ODS 3, Length: 1668, dtype: float64

In [ ]:
#Qual a cidade do estado que reponde corretamente o item anterior,
#e que teve o valor da “ODS ano 2022” mais próximo da média do estado inteiro?